name: Commits

on:
  pull_request:

jobs:
  commitlint:
    name: Conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-action@b948dc23e8f97a63b8ea20cf3a68fd0b3e1a1c1b # v6
        with:
          configFile: .commitlintrc.json
