name: Release Please

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_TOKEN }}

    - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
      id: release_please
      with:
        release-type: go
        path: .
        token: ${{ secrets.RELEASE_TOKEN }}
        default-branch: main
        fork: false
